#!/bin/sh

setxkbmap fr_intl & 
xsetroot -cursor_name left_ptr &
dunst &
# maill &
restt &
# splash &
batbat &
cookie &
# tint2 &
# wal -R & 
# polybar main &
compton -b &
numlockx &
# netwmpager &
hsetroot -solid "f0f0f2" &
# hsetroot -solid "#d4d7de" &
xgamma -gamma 0.9 &
sleep 3s && xrandr --dpi 102
xfce4-power-manager &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

exec fluxbox

