#!/bin/bash
pkill n30f
	MUSIC_DIR=/run/media/onodera/Miso/Music/
	COVER=/tmp/cover.png
	bg=/tmp/begron.png
    back="$HOME/.covers/cover3.png"
    
{	album="$(mpc -p 6600 --format %album% current)"
    file="$(mpc -p 6600 --format %file% current)"
    album_dir="${file%/*}"
    [[ -z "$album_dir" ]] && exit 1
    album_dir="$MUSIC_DIR/$album_dir"
    covers="$(find "$album_dir" -type d -exec find {} -maxdepth 1 -type f -iregex ".*/.*\(${album}\|cover\|folder\|artwork\|front\).*[.]\(jpe?g\|png\|gif\|bmp\)" \; )"
    src="$(echo -n "$covers" | head -n1)"
    rm -f "$COVER" 
    convert "$src" -resize 250 "$COVER"
	convert "$back" -resize 20 "$bg"
    n30f -x 669 -y 677 -d ${bg}
    n30f -x 555 -y 420 -d ${COVER}
} &
