#! /bin/sh

#                    ___           ___         ___           ___
#     _____         /  /\         /  /\       /__/\         /__/\
#    /  /::\       /  /:/_       /  /::\     _\_ \:\       |  |::\
#   /  /:/\:\     /  /:/ /\     /  /:/\:\   /__/\ \:\      |  |:|:\  
#  /  /:/~/::\   /  /:/ /::\   /  /:/~/:/  _\_ \:\ \:\   __|__|:|\:\
# /__/:/ /:/\:| /__/:/ /:/\:\ /__/:/ /:/  /__/\ \:\ \:\ /__/::::| \:\ 
# \  \:\/:/~/:/ \  \:\/:/~/:/ \  \:\/:/   \  \:\ \:\/:/ \  \:\~~\__\/ 
#  \  \::/ /:/   \  \::/ /:/   \  \::/     \  \:\ \::/   \  \:\
#   \  \:\/:/     \__\/ /:/     \  \:\      \  \:\/:/     \  \:\
#    \  \::/        /__/:/       \  \:\      \  \::/       \  \:\
#     \__\/         \__\/         \__\/       \__\/         \__\/



###############
## autostart ##
###############

# xrandr
sleep 3s && xrandr --dpi 102

# cookies to make my day better
cookie &

# keybind daemon
sxhkd &

# volume icon
# pa-applet &

## load dunst
dunst &

## reload compton
compton -b &

# load cursor theme
xsetroot -cursor_name left_ptr

# dat annoying numblock
numlockx

# authentification
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# stupid azerty keyboard workaround
# setxkbmap -layout be

# Battery notif
batbat &

# tint2 
# tint2 &

# power manager
xfce4-power-manager

# autostart polybar
# If you are using bspwm, add the following line to bspwmrc:
# $HOME/.config/polybar/launch

# hsetroot and solid wallpapers
# hsetroot -solid "#9ccfe6" &
# hsetroot -solid "#d4d7de &
hsetroot -solid "#ffd5c0" &                                                    

# gamma
xgamma -gamma 0.9 &


## workspace name
bspc monitor -d 1 2 3 4 5 6 7 8 


## common bspwm configuration
bspc config top_padding        1
bspc config bottom_padding     1
bspc config left_padding       1
bspc config right_padding      1
bspc config border_width       0
bspc config window_gap         8
bspc config border_radius      -20

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      false


##################
## window rules ##
##################

bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a URxvt state=floating
bspc rule -a feh state=floating 
bspc rule -a mpv state=floating
bspc rule -a Thunar state=floating
bspc rule -a Termite state=floating
bspc rule -a Mousepad state=floating
bspc rule -a Nautilus state=floating
bspc rule -a Pamac-manager state=floating

## don't manage my conky & systemtray
bspc rule -a Conky state=floating manage=off
bspc rule -a stalonetray state=floating manage=off

# pywal
# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "#1d383e"
bspc config active_border_color "#1d383e"
bspc config focused_border_color "$foreground"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$foreground"
# Use the line below if you are on bspwm < 0.9.4
#bspc config presel_border_color "$foreground"

# tried using this to restore the wallpaper and colorsheme on reload/restart and it seems to work
# wal -R

# Load random "Light" colorscheme on startup
# wal -i $HOME/Pictures/Wallpapers -l -o wal-set

# Load random "Dark" colorscheme on startup
# wal -i $HOME/Pictures/Wallpapers -o wal-set


