#!/usr/bin/env bash
#
# This script will alert when battery is less than 20% and discharging
# Created by Daniel Neemann

while :; do 
	n=$(cat /sys/class/power_supply/BAT1/capacity)
	y=$(cat /sys/class/power_supply/BAT1/status)
	if [ "$n" -lt "15" ] && [ "$y" = "Discharging" ]; then
	pkill dunst && notify-send -u critical "BITCH I'M DYING $n%"
        elif [ "$n" -gt "95" ] && [ "$y" = "Charging" ]; then
        pkill dunst && notify-send -u critical "BITCH I'M FULL $n%"
        fi
	sleep 2m
done