#!/usr/bin/env bash
# requires urxvt, slop, xdotool and wmctrl.

# vars
border="6"
color="255 255 255 0"
format="%w %h %x %y"
dir="/usr/local/bin"


# exec
urxvt -iconic -name "demons" &
read "width" "height" "xpos" "ypos" < <(slop -l -f "$format" -b "$border" -c "$color")

if [ "$width" ] ; then
	:
else
	pkill -n -f "urxvt -iconic -name demons"
	exit "1"
fi

# adapt to the border width of your windows
((width -= 5))
((height -= 10))

active="$(xdotool search --sync --classname demons | tail -n1)"

xdotool "windowmove" "$active" "$xpos" "$ypos"
xdotool "windowsize" "$active" "$width" "$height"
wmctrl -ia "$active"