#!/bin/bash

pkill lemonbar

bg="%{B#343d46}%{F#bfbec3}"
active="%{B#343d46}%{F#ffffff}"
geo="1366x30+0+0"
f1="euphon:size=8"

swsa="$bg%{B-}%{F-}"
swsn="$bg%{B-}%{F-}"

get_ws(){
    desk=$(xdotool get_desktop)
    wsname=("     Fate    " "    Stay    " "    Night    ")
    for i in {0..3}; do
        echo -n "$bg%{A:xdotool set_desktop $i:}"
        if [[ "$((desk))" == "$i" ]]; then
            echo -n "$swsa$active"
        else
            echo -n ""
        fi
        if [[ "$((desk))" == "$i" ]]; then
            echo -n "${wsname[$((i))]}$swsn" | tr '[:lower:]' '[:lower:]'
        else
            echo -n "${wsname[$((i))]}" | tr '[:lower:]' '[:lower:]'
        fi
        echo -n "%{A}%{B-}%{F-}"
done
}

get_window(){	
	id=$(xtitle -t 50)
	echo "%{B#37bf8d}%{F#ffffff}    $id    %{B-}%{F-}"
}

get_weather() {
        echo "%{B#343d46}%{F#c0c5ce}    $(wewe)    %{B-}%{F-}"
}

get_song(){
    echo "%{B#12171f}%{F#ffffff}%{A:mpc toggle:}%{A2:bum --size "200":}    $(mpcc)    %{A}%{B-}%{F-}"
}

get_time() {
        echo "%{B#2b303b}%{F#c0c5ce}%{A:tint2 -c $HOME/.config/tint2/calright.tint2rc:} TODAY AT $(date +'%H:%M') %{A}%{B-}%{F-}"
}

while true; do
    echo "%{B#12171f}%{5}%{O0}$(get_window)$(get_ws) %{c} $(get_time)%{O0} %{r} $(get_weather)%{O0}"
    sleep 1
done | lemonbar -g "${geo}" -f "${f1}" -B "#2b303b" -F "#ffffff" -o 1 -a 25 -b | sh & > /dev/null
