#!/bin/bash

pkill lemonbar

bg="%{B#000000}%{F#bfbec3}"
active="%{B#000000}%{F#ffffff}"
geo="1366x35+0+0"
f1="metis:size=8"
f1="metis:size=8"

swsa="$bg%{B-}%{F-}"
swsn="$bg%{B-}%{F-}"


get_ws(){
    desk=$(xdotool get_desktop)
    wsname=(" ichi " " ni " " san " " yon ")
    for i in {0..3}; do
        echo -n "$bg%{A:xdotool set_desktop $i:}"
        if [[ "$((desk))" == "$i" ]]; then
            echo -n "$swsa$active"
        else
            echo -n ""
        fi
        if [[ "$((desk))" == "$i" ]]; then
            echo -n "${wsname[$((i))]}$swsn" | tr '[:lower:]' '[:lower:]'
        else
            echo -n "${wsname[$((i))]}" | tr '[:lower:]' '[:lower:]'
        fi
        echo -n "%{A}%{B-}%{F-}"
done
}

get_time() {
        echo "%{B#000000}%{F#ffffff} TODAY AT $(date +'%H:%M') %{B-}%{F-}"
}

while true; do
    echo " %{B#000000}%{5}%{O5}$(get_ws) \
    %{r} $(get_time)%{O5} "
    sleep 1
done | lemonbar -g "${geo}" -f "${f1}" -B "#000000" -F "#ffffff" -u 4 -a 25 | sh & > /dev/null
