#!/bin/bash

pkill lemonbar

bg="%{B#ff6636}%{F#ffffff}"
active="%{B#ff754a}%{F#ffffff}"
geo="1366x30+0+0"
f1="euphon:size=8"
f2="bitbuntufull:size=8"
f3="Baekmuk Batang:size=8"

swsa="$bg%{B-}%{F-}"
swsn="$bg%{B-}%{F-}"

get_ws(){
    desk=$(xdotool get_desktop)
    wsname=("     אחד    " "    שתיים    " "    שלוש    ")
    for i in {0..3}; do
        echo -n "$bg%{A:xdotool set_desktop $i:}"
        if [[ "$((desk))" == "$i" ]]; then
            echo -n "$swsa$active"
        else
            echo -n ""
        fi
        if [[ "$((desk))" == "$i" ]]; then
            echo -n "${wsname[$((i))]}$swsn" | tr '[:lower:]' '[:lower:]'
        else
            echo -n "${wsname[$((i))]}" | tr '[:lower:]' '[:lower:]'
        fi
        echo -n "%{A}%{B-}%{F-}"
done
}

get_window(){	
	id=$(xtitle -t 50)
	echo "%{B#ff6636}%{F#ffffff}      $id      %{B-}%{F-}"
}

get_weather() {
        echo "%{B#343d46}%{F#c0c5ce}    $(wewe)    %{B-}%{F-}"
}

get_song(){
    echo "%{B#343d46}%{F#c0c5ce}%{A:mpc toggle:}%{A3:popup-night:}%{A2:pkill n30f:}     $(mpcc)     %{A}%{A}%{A}%{B-}%{F-}"
}

get_time() {
        echo "%{B#2b303b}%{F#c0c5ce}%{A:todo show:} $(date "+%a %R") %{A}%{B-}%{F-}"
}

while true; do
    echo "%{B#12171f}%{5}%{O0}$(get_window)$(get_ws) %{c} $(get_time)%{O0} %{r} $(get_song)%{O0}"
    sleep 1
done | lemonbar -g "${geo}" -f "${f1}" -f "${f2}" -f "${f3}" -B "#2b303b" -F "#ffffff" -o 1 -a 25 -b | sh & > /dev/null
