#!/bin/bash
#
# onodera - onodera at openmailbox dot org
# Display some rice info

foreground="\e[0;39m"
brown="\e[1;33m"

hostname="$(hostname)"
distro="$(lsb_release -is)"
kernel="$(uname -r -s)"
uptime="$(uptime -p | cut -d " " -f 2-)"
packages="666"
shell="$(basename ${SHELL})"

if [ -z "${WM}" ]; then
	if [ "${XDG_CURRENT_DESKTOP}" ]; then
		envtype='WM'
		WM="${XDG_CURRENT_DESKTOP}"
	elif [ "${DESKTOP_SESSION}" ]; then
		envtype='WM'
		WM="${DESKTOP_SESSION}"
	else
		envtype='WM'
		WM="$(tail -n 1 "${HOME}/.xinitrc" | cut -d ' ' -f 2)"
	fi
else
	envtype='WM'
fi


# Echo rice
echo -e '    .---､ '        
echo -e '    |· ·| '
echo -e '    | ゝ| '"      ${brown}Distro:$foreground    $distro"
echo -e '   ΣIIIII '"      ${brown}Kernel:$foreground    $kernel"
echo -e '    |   | '"      ${brown}Uptime:$foreground    $uptime"
echo -e '    |   | '"      ${brown}Packages:$foreground  $packages"
echo -e '    |___| '"      ${brown}$envtype:$foreground        $WM"
echo -e '     | | '"       ${brown}shell:$foreground     $shell"
echo -e '     └ └ '

      
